################################################################################
# Run OS dependent tasks
################################################################################

- name: deploy | Run OS dependent tasks
  include_tasks: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - "tasks/deploy-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "tasks/deploy-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "tasks/deploy-{{ ansible_distribution }}.yml"
      - "tasks/deploy-{{ ansible_os_family }}.yml"
